linn/stores2

src/Domain.LinnApps/Stock/StorageLocation.cs, src/Domain.LinnApps/Stock/StorageType.cs, src/Facade/ResourceBuilders/StockPoolResourceBuilder.cs, src/Facade/ResourceBuilders/StorageLocationResourceBuilder.cs, src/Facade/Services/StorageLocationService.cs, src/IoC/HandlerExtensions.cs, src/IoC/PersistenceExtensions.cs, src/IoC/ServiceExtensions.cs, src/Persistence.LinnApps/Repositories/StorageLocationRepository.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Resources/StorageLocationResource.cs, src/Service.Host/client/src/components/Root.js, src/Service.Host/client/src/components/StorageLocation.js, src/Service.Host/client/src/components/StorageLocations.js, src/Service.Host/client/src/itemTypes.js, src/Service/Modules/StorageModule.cs, tests/Integration/Integration.Tests/StockPoolModuleTests/WhenGettingAll.cs, tests/Integration/Integration.Tests/StockPoolModuleTests/WhenGettingById.cs, tests/Integration/Integration.Tests/StockPoolModuleTests/WhenUpdating.cs, tests/Integration/Integration.Tests/StorageModuleTests/ContextBase.cs, tests/Integration/Integration.Tests/StorageModuleTests/WhenGettingAllLocations.cs, tests/Integration/Integration.Tests/StorageModuleTests/WhenGettingAllSites.cs, tests/Integration/Integration.Tests/StorageModuleTests/WhenSearchLocationsBySiteAndArea.cs, tests/Integration/Integration.Tests/StorageModuleTests/WhenSearchingLocations.cs
location ut 
- search for location
- view a location
- start of create link
=> Locationut1

src/Service.Host/client/src/components/Root.js, src/Service.Host/client/src/components/StorageTypes.js, src/Service.Host/client/src/itemTypes.js
=> Storage types2

src/Domain.LinnApps/Exceptions/StorageLocationException.cs, src/Domain.LinnApps/External/IDatabaseSequenceService.cs, src/Domain.LinnApps/Stock/StorageLocation.cs, src/Facade/ResourceBuilders/StorageLocationResourceBuilder.cs, src/Facade/Services/StorageLocationService.cs, src/IoC/ServiceExtensions.cs, src/Persistence.LinnApps/Repositories/StorageLocationRepository.cs, src/Persistence.LinnApps/Repositories/StorageSiteRepository.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Proxy/DatabaseSequenceService.cs, src/Proxy/RequisitionStoredProcedures.cs, src/Resources/StorageLocationResource.cs, src/Service.Host/client/src/components/StorageLocation.js, src/Service.Host/client/src/components/StorageLocations.js, src/Service.Host/client/src/itemTypes.js, src/Service/Modules/StorageModule.cs, tests/Integration/Integration.Tests/StorageModuleTests/ContextBase.cs, tests/Integration/Integration.Tests/StorageModuleTests/WhenCreatingLocation.js.cs, tests/Integration/Integration.Tests/TestDatabaseSequenceService.cs, tests/Unit/Domain.LinnApps.Tests/StorageLocationTests/WhenCreatingAndInvalidAccessibleSupplied.cs, tests/Unit/Domain.LinnApps.Tests/StorageLocationTests/WhenCreatingAndInvalidLocationCodePrefix.cs, tests/Unit/Domain.LinnApps.Tests/StorageLocationTests/WhenCreatingAndInvalidMixStates.cs, tests/Unit/Domain.LinnApps.Tests/StorageLocationTests/WhenCreatingAndInvalidStoreState.cs, tests/Unit/Domain.LinnApps.Tests/StorageLocationTests/WhenCreatingAndInvalidStoresKittable.cs, tests/Unit/Domain.LinnApps.Tests/StorageLocationTests/WhenCreatingAndInvalidTypeOfStock.cs, tests/Unit/Domain.LinnApps.Tests/StorageLocationTests/WhenCreatingAndNoAreaSupplied.cs, tests/Unit/Domain.LinnApps.Tests/StorageLocationTests/WhenCreatingAndNoCompanySupplied.cs, tests/Unit/Domain.LinnApps.Tests/StorageLocationTests/WhenCreatingAndNoSiteSupplied.cs
adds more fields to locationut
ability to create locations
=> Locationut2

src/Domain.LinnApps/Requisitions/RequisitionHeader.cs, src/Domain.LinnApps/Requisitions/RequisitionService.cs, src/Facade/ResourceBuilders/RequisitionResourceBuilder.cs, src/Facade/Services/StorageTypeFacadeService.cs, src/Persistence.LinnApps/Repositories/RequisitionRepository.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Resources/Requisitions/RequisitionHeaderResource.cs, src/Service.Host/client/src/components/requisitions/Requisition.js, src/Service.Host/client/src/components/requisitions/components/DepartmentNominal.js, src/Service.Host/client/src/components/requisitions/reducers/requisitonReducer.js
change shouldRender to receive function as param
move dept nom to sub comp
continue rename of functionCode to storesFunction
=> more annoying changes

src/Domain.LinnApps/AuthorisedActions.cs, src/Domain.LinnApps/Exceptions/UnauthorisedActionException.cs, src/Domain.LinnApps/Requisitions/IRequisitionService.cs, src/Domain.LinnApps/Requisitions/LineCandidate.cs, src/Domain.LinnApps/Requisitions/MoveSpecification.cs, src/Domain.LinnApps/Requisitions/RequisitionHeader.cs, src/Domain.LinnApps/Requisitions/RequisitionLine.cs, src/Domain.LinnApps/Requisitions/RequisitionService.cs, src/Facade/Services/RequisitionFacadeService.cs, src/IoC/PersistenceExtensions.cs, src/Persistence.LinnApps/ServiceDbContext.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionServiceTests/ContextBase.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionServiceTests/WhenBookingAndUnauthorised.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionServiceTests/WhenCancellingAndUnauthorised.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionServiceTests/WhenCancellingLineAndUnauthorised.cs
- really just an outline of a plan but PR'ing to avoid conflicts
=> Raise ldreqs first bits

src/Service.Host/client/src/components/requisitions/PendingRequisitions.js, src/Service.Host/client/src/components/requisitions/Requisition.js, src/Service.Host/client/src/components/requisitions/components/AuthBy.js, src/Service.Host/client/src/helpers/__tests__/strings.js, src/Service.Host/client/src/hooks/useSearch.js
=> make lint less red

src/Domain.LinnApps/Requisitions/IRequisitionManager.cs, src/Domain.LinnApps/Requisitions/ReqMove.cs, src/Domain.LinnApps/Requisitions/RequisitionManager.cs, src/Facade/Common/AsyncFacadeService.cs, src/Facade/Services/RequisitionFacadeService.cs, src/Resources/Requisitions/RequisitionLineResource.cs, src/Service.Host/client/src/components/requisitions/LinesTab.js, src/Service.Host/client/src/components/requisitions/Requisition.js, src/Service.Host/client/src/components/requisitions/reducers/requisitonReducer.js, src/Service/Modules/RequisitionModule.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionMoveTests/WhenSettingFieldsFromHeader.cs
very rough pick stock on loan out doesn't actually move the stock but sends it into the ether
don't think this is the fault of pick stock
=> first version only does a from and not a move

src/Service.Host/client/src/components/PartsStorageTypes.js
=> fix column width

src/Domain.LinnApps/Requisitions/RequisitionHeader.cs, src/Service.Host/client/src/components/requisitions/LinesTab.js, src/Service.Host/client/src/components/requisitions/MovesTab.js, src/Service.Host/client/src/components/requisitions/PickStockDialog.js, src/Service.Host/client/src/components/requisitions/Requisition.js, src/Service.Host/client/src/components/requisitions/components/DepartmentNominal.js, src/Service.Host/client/src/components/requisitions/reducers/requisitonReducer.js, src/Service.Host/package-lock.json, src/Service.Host/package.json, tests/Unit/Domain.LinnApps.Tests/RequisitionHeaderTests/WhenAddingLineAndBooked.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionHeaderTests/WhenUpdatingAndBooked.cs
- just more miscellaneous bits, pring to reduce conflict
=> Ldreq checking

src/Facade/ResourceBuilders/RequisitionResourceBuilder.cs, src/Facade/ResourceBuilders/StoresFunctionResourceBuilder.cs, src/Service.Host/client/src/components/requisitions/Requisition.js, src/Service/Modules/RequisitionModule.cs, tests/Integration/Integration.Tests/RequisitionModuleTests/ContextBase.cs
the real function code permission check
=> function code permission check

src/Domain.LinnApps/Requisitions/CreationStrategies/GistPoCreationStrategy.cs, src/Domain.LinnApps/Requisitions/RequisitionHeader.cs, src/Service.Host/client/src/components/requisitions/Requisition.js, src/Service.Host/client/src/hooks/usePost.js, tests/TestData/TestData/FunctionCodes/TestFunctionCodes.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionHeaderTests/WhenCreatingAndNoFromLocationOrPalletWhenRequiredByStoresFunction.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionHeaderTests/WhenCreatingAndNoFromStockPoolWhenRequiredByStoresFunction.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionHeaderTests/WhenCreatingAndNoToLocationOrPalletWhenRequiredByStoresFunction.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionHeaderTests/WhenCreatingAndNoToStateWhenRequiredByStoresFunction.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionHeaderTests/WhenTryingToBookSupplierKitAndQtiesDontMatch.cs
- this idea runs the validation request every time formState changes, but with a seconds debounce - i.e. it will only run the validation if no further changes have happened for one second
- I also added abort controller stuff to usePost to allow cancelling requests. In this example i'm cancelling a validation request whenever a new one is made, although in practise I dont really see this happening since validate responses take less time to arrive than my debounce time of 1 second
=> debounce validation idea

src/Domain.LinnApps/Requisitions/CreationStrategies/CustRetCreationStrategy.cs, src/Domain.LinnApps/Requisitions/IRequisitionManager.cs, src/Domain.LinnApps/Requisitions/RequisitionHeader.cs, src/Domain.LinnApps/Requisitions/RequisitionManager.cs, src/Service.Host/client/src/components/requisitions/Requisition.js, src/Service.Host/client/src/components/requisitions/components/Document1.js, src/Service.Host/client/src/itemTypes.js, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenCheckingDocumentLineAndFullyBooked.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenCheckingDocumentLineAndOverBooked.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenGettingDocumentAndCreditNoteLineIsCancelled.cs
first branch that actually allows CUSTRET to work although it is still a bit clunky having to fill out To State and Stock Pool Code which are defaulted in REQ_UT
=> first viable CUSTRET functionality

src/Domain.LinnApps/Requisitions/RequisitionManager.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenAddingLineAndSuReqNotManualPick.cs
allow automatic picking in SUREQ when manual pick is No
=> automatic picking of stock when manual pick is No

src/Domain.LinnApps/Requisitions/RequisitionManager.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingGistPo.cs
- I should really extend this out to explicitly check the batch ref is correct for the docType, but just to get us moving as running out of time today
=> allow returns orders in a somewhat hack way for now

src/Domain.LinnApps/Requisitions/RequisitionManager.cs, src/Domain.LinnApps/Requisitions/StoresFunction.cs, tests/TestData/TestData/FunctionCodes/TestFunctionCodes.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingSupplierKit.cs
To get a SUKIT past the validation
need to go contrary to some existing rules with an unwield functionCode == "SUKIT" will refactor when i get a chance to rethink how the logic ought to work
=> allow SUKIT past the validation

src/Service.Host/client/src/components/requisitions/PickStockDialog.js, src/Service.Host/client/src/components/requisitions/components/StockOptions.js
Use select row automation only for single batch selection (front page) so as not to disrupt manual selection (from lines tab).
Rename parameter from getBatches to selectSingleBatch to make it a tiny bit clearer.
=> change as per feedback

src/Domain.LinnApps/Requisitions/RequisitionLine.cs, src/Domain.LinnApps/Requisitions/RequisitionSerialNumber.cs, src/Facade/ResourceBuilders/RequisitionLineResourceBuilder.cs, src/Persistence.LinnApps/Repositories/RequisitionRepository.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Resources/Requisitions/RequisitionLineResource.cs, src/Resources/Requisitions/RequisitionSerialNumberResource.cs, src/Service.Host/client/src/components/requisitions/Requisition.js, src/Service.Host/client/src/components/requisitions/SerialNumbersTab.js, src/Service.Host/client/src/components/requisitions/components/Document1.js, src/Service.Host/client/src/components/requisitions/reducers/requisitonReducer.js, tests/Unit/Domain.LinnApps.Tests/RequisitionLineTests/WhenAddingDuplicateRequisitionSerialNumber.cs
req sernos skeleton
+ mark fix for CUSTRET
=> basic req sernos

src/Facade/ResourceBuilders/RequisitionLineResourceBuilder.cs
=> hopefully works

src/Service.Host/client/src/components/StorageLocations.js
for mark's wish to do faster invaliding of bunches of locations
=> bulk invalidator for stock locators

src/Domain.LinnApps/Requisitions/RequisitionManager.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAdjust.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAndHeaderSpecifiesInvalidPalletNumber.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAndHeaderSpecifiesNonExistentToPallet.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAndHeaderSpecifiesNonExistentToState.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAndHeaderSpecifiesNonExistentToStockPool.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAndMoveHasNoQty.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAndMoveMissingLocation.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAndMoveMissingOnToLocation.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAndMoveOntoSpecifiesInvalidPallet.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAndMoveOntoSpecifiesNonExistingPallet.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAndMovesFromSpecifyBothLocationCodeAndPallet.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAndNoLinesWhenRequiredByStoresFunction.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAndNoMovesOntoWhenSpecifiedByLineTransaction.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAndSecondLineHasNoQty.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAudit.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAuditAndAuditLocationDoesNotExist.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingAuditNotEnoughStock.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingLdReqButInvalidDeptNominal.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingLdReqOntoStock.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingLdReqOntoStockAndHeaderSpecifiesToLocation.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingLdReqOntoStockWithLocButNoStockPool.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingLdreqFromStock.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingPartNumberChange.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingPartNumberChangeAndInvalidPartNumberChange.cs, tests/Unit/Domain.LinnApps.Tests/RequisitionManagerTests/WhenValidatingWOff.cs
=> check department and nominal when validating req

src/Domain.LinnApps/Requisitions/ReqMove.cs, src/Domain.LinnApps/Requisitions/RequisitionManager.cs, src/Service.Host/client/src/components/requisitions/MovesTab.js, src/Service.Host/client/src/components/requisitions/Requisition.js, src/Service.Host/client/src/components/requisitions/components/UnpickMoveDialog.js, tests/Unit/Domain.LinnApps.Tests/ReqMoveTests/WhenUnpickingFullAmount.cs, tests/Unit/Domain.LinnApps.Tests/ReqMoveTests/WhenUnpickingPartialAmount.cs
extra bit of unpick to make it work
=> second part of unpick

src/Service.Host/client/src/components/requisitions/Requisition.js
Accomodate rare occasions that Ewan does a RSN for an Onto Req Type
Has three to do at the moment and old form allowed it
=> for rare type of RSN

src/Domain.LinnApps/Models/DeliveryNoteDocument.cs, src/Domain.LinnApps/Requisitions/DeliveryNoteService.cs, src/Service.Host/views/DeliveryNoteDocument.cshtml
for ColinW on ticket 20738 add comments to delivery note
=> extra field on SUKIT delivery note

src/Domain.LinnApps/External/ICalcLabourHoursProxy.cs, src/Domain.LinnApps/Parts/Bom.cs, src/Domain.LinnApps/Parts/Part.cs, src/Domain.LinnApps/Reports/IStockReportService.cs, src/Domain.LinnApps/Reports/LabourHoursSummary.cs, src/Domain.LinnApps/Reports/StockReportService.cs, src/Domain.LinnApps/Stock/TqmsData.cs, src/Facade/Services/IStockReportFacadeService.cs, src/Facade/Services/StockReportFacadeService.cs, src/IoC/HandlerExtensions.cs, src/IoC/PersistenceExtensions.cs, src/IoC/ServiceExtensions.cs, src/Persistence.LinnApps/Repositories/TqmsDataRepository.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Proxy/StoredProcedureClients/CalcLabourTimesProxy.cs, src/Resources/TotalResource.cs, src/Service.Host/client/src/components/App.js, src/Service.Host/client/src/components/LabourHoursInStockReport.js, src/Service.Host/client/src/components/LabourHoursSummaryReport.js, src/Service.Host/client/src/components/Root.js, src/Service.Host/client/src/itemTypes.js, src/Service.Host/index.html, src/Service/Modules/StockReportModule.cs, tests/Integration/Integration.Tests/StockReportModuleTests/ContextBase.cs, tests/Integration/Integration.Tests/StockReportModuleTests/WhenGettingLabourHoursInStockReport.cs, tests/Integration/Integration.Tests/StockReportModuleTests/WhenGettingLabourHoursInStockTotal.cs, tests/Unit/Domain.LinnApps.Tests/StockReportServiceTests/ContextBase.cs, tests/Unit/Domain.LinnApps.Tests/StockReportServiceTests/WhenGettingLabourSummary.cs, tests/Unit/Domain.LinnApps.Tests/TqmsDataTests/WhenGettingLabourHours.cs
two labour hours in stock reports one for month end, one for year end
- month end labour hours in stock 
- year end labour hours summary
both are quite slow to run especially the year end one.
=> Labourhours

src/Domain.LinnApps/Reports/StockReportService.cs, tests/Unit/Domain.LinnApps.Tests/StockReportServiceTests/WhenGettingLabourHoursInLoans.cs
report fixes to make labour hours in loans agree with production report
=> report fixes
